### ISSUE TITLE
Integer Overflow

### ISSUE THREAD

**Issue by mertakdut** [Rillke/flac.js#11]
flac.js outputs _integer overflow_ exception for specific type of data. Here is the [wav file](https://www.dropbox.com/s/w6s1mkmht2h8zg8/portal.wav?dl=0) and the code to reproduce the error.

```
var file = document.getElementById('file').files[0];

var reader = new FileReader();

reader.onload = function (e) {
  worker = new Worker('../assets/worker/EmsWorkerProxy.js');
  worker.onmessage = onWorkerMessage;
  worker.onerror = onWorkerError;

  var encodedName = file.name.replace(/\.[^\.]+$/, '.flac');
  console.log('encoding ' + file.name + ' to ' + encodedName);

  var args = [
    file.name
  ];

  var inData = {};
  inData[file.name] = new Uint8Array(reader.result);
  console.log(inData[file.name]);

  var outData = {};
  outData[encodedName] = {
    // Its MIME type
    'MIME': 'audio/flac'
  };

  worker.postMessage({
    command: 'encode',
    args: args,
    outData: outData,
    fileData: inData
  });
}

reader.readAsArrayBuffer(file);
```

Probably the same thing happens in the [sample site](https://rawgit.com/Rillke/flac.js/master/iframe.html). In my code it gets broken when the progress is 71% complete, can't see the sample site's logs but the [progress bar is stucked around 70%.](https://www.dropbox.com/s/rcdp2th9czqrj51/stuck_progress_bar.png?dl=0)

Flac CLI works perfectly fine. Tested on version [1.3.2 win64](https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.2-win.zip).

**Comment by Rillke** [comment]
flac seems to do some [float-to-integer](https://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#binaryen-codegen-options) conversion that fails. That is why the wasm build may fail. Fixed with 1c530b5333a85d3d9fe5c4d6384169ae6da16e7c.
Thanks for the report.
