### ISSUE TITLE
Encoding .amr files

### ISSUE THREAD

**Issue by Sokoho** [Rillke/flac.js#4]
Hello,

First I want to thank you for the wonderful work you did with this project, it works perfectly for me when I try to encode wav files.

Then my problem: when I use it to encode amr file into flac, it doesn't work. I know you don't say in the README.md that amr is a supported format. So I wonder: is there a simple way to modify the encoder so that it can support amr input files?

**Comment by Rillke** [comment]
Thanks.

Unfortunately, I see no way making the encoder supporting [`.amr`](https://en.wikipedia.org/wiki/Adaptive_Multi-Rate_audio_codec) files other than first decoding them (either to raw or wave) and using the decoded result for `flac` encoding.

Please feel free to re-open the issue if there is more to talk about.
