### ISSUE TITLE
question: is it possible to stream encode/decode?

### ISSUE THREAD

**Issue by tyler-g** [Rillke/flac.js#5]
I'm looking for a way to encode buffers of WAV data to a compressed lossless format on the fly (doesn't have to be FLAC but it seems like a good option).  Is it theoretically possibly to edit this library to do that?  I know a good bit about WAV format but not much at all about FLAC.

In other words, the source buffer would be a single sample of WAV encoded data, and I'd want to encode that single buffer to FLAC data.

Thanks for this great tool

**Comment by Rillke** [comment]
Part of that should be possible with `--force-raw-format`

```
raw format options:
      --endian={big|little}    Set byte order for samples
      --channels=#             Number of channels
      --bps=#                  Number of bits per sample
      --sample-rate=#          Sample rate in Hz
      --sign={signed|unsigned} Sign of samples
      --input-size=#           Size of the raw input in bytes
```

Note that the output will be a complete flac-file though (or a typed array containing the file data including headers etc).

Fine tuning may either require modifying the [en/de-coder's main method](https://github.com/Rillke/flac/blob/ad5eba14a21b303a50c132a69bc92362113444fa/src/flac/main.c#L299) or exposing some functions by the flac library [during compilation with Emscripten](https://github.com/Rillke/flac.js/blob/master/make.sh#L40).

Unfortunately, I do not have the resources to deliver that at the moment.

**Comment by tyler-g** [comment]
thanks @Rillke for the update – I may be able to dive into a little though not at the moment.   I was able to tweak another library "libflac.js" which I believe is very similar to yours?  It is an emscripten port of libflac.   I still haven't figured out on-the-fly decoding through
